### ISSUE TITLE
Non-ASCII characters in git name lead to: UnicodeDecodeError

### ISSUE THREAD

**Issue by hroncok** [encukou/rpm-spec-merge-driver#1]
```
Traceback (most recent call last):
  File "/home/churchyard/.local/bin/rpm-spec-merge-driver", line 213, in main
    new_entry = new_spec.changelog.squash(main_spec.changelog, max_version, release)
  File "/home/churchyard/.local/bin/rpm-spec-merge-driver", line 144, in squash
    header = get_changelog_header(version, release)
  File "/home/churchyard/.local/bin/rpm-spec-merge-driver", line 172, in get_changelog_header
    proc = subprocess.run(
  File "/usr/lib64/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.8/subprocess.py", line 1011, in communicate
    stdout = self.stdout.read()
  File "/usr/lib64/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 41: ordinal not in range(128)
```

Is suppose that is `č` in my name.

**Comment by encukou** [comment]
This still wants a test.

**Comment by hroncok** [comment]
On it.

**Comment by hroncok** [comment]
Oh, so the merge drive user is "hardcoded" in tests, not part of the test cases. I wonder how to properly test it. Easiest seem to always set the git user to something a tad weird. What about `Naïve Merge Driver User` or `Merge Driver 💁`

**Comment by encukou** [comment]
Sounds good

**Comment by hroncok** [comment]
https://github.com/encukou/rpm-spec-merge-driver/pull/5
